gestor/urls.py
from django.urls import path

from . import views

app_name = 'gestor'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path("read/",views.ListTareaAPIView.as_view(),name="tarea_list"),
    path("create/", views.CreateTareaAPIView.as_view(),name="tarea_create"),
    path("update/<int:pk>/",views.UpdateTareaAPIView.as_view(),name="update_tarea"),
    path("delete/<int:pk>/",views.DeleteTareaAPIView.as_view(),name="delete_tarea")
]

proyectocrud/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('gestor.urls')),
    path('admin/', admin.site.urls),
]

gestor/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib import admin

# Create your models here.

class Tarea(models.Model):
    titulo_text = models.CharField(max_length=200)
    descripcion_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('Fecha de creacion')

    def __str__(self):
        return self.titulo_text

    @admin.display(
        boolean=True,
        ordering='pub_date',
        description='Published recently?',
    ) 

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Empleado(models.Model):
    tarea = models.ForeignKey(Tarea, on_delete=models.CASCADE)
    nombre_text = models.CharField(max_length=200)

    def __str__(self):
        return self.nombre_text

gestor/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from rest_framework.generics import ListAPIView
from rest_framework.generics import CreateAPIView
from rest_framework.generics import DestroyAPIView
from rest_framework.generics import UpdateAPIView
from gestor.serializers import TareaSerializer
from .models import Empleado, Tarea

# Create your views here.

class IndexView(generic.ListView):
    template_name = 'gestor/index.html'
    context_object_name = 'latest_tarea_list'

    def get_queryset(self):
        return Tarea.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Tarea 
    template_name = 'gestor/detail.html'

# Create your views here.
class ListTareaAPIView(ListAPIView):
    """This endpoint list all of the available todos from the database"""
    queryset = Tarea.objects.all()
    serializer_class = TareaSerializer

class CreateTareaAPIView(CreateAPIView):
    """This endpoint allows for creation of a todo"""
    queryset = Tarea.objects.all()
    serializer_class = TareaSerializer

class UpdateTareaAPIView(UpdateAPIView):
    """This endpoint allows for updating a specific todo by passing in the id of the todo to update"""
    queryset = Tarea.objects.all()
    serializer_class = TareaSerializer

class DeleteTareaAPIView(DestroyAPIView):
    """This endpoint allows for deletion of a specific Todo from the database"""
    queryset = Tarea.objects.all()
    serializer_class = TareaSerializer

gestor/templates/gestor/detail.html
<h1>{{ tarea.titulo_text }}</h1>
<ul>
{% for empleado in tarea.empleado_set.all %}
    <li>{{ empleado.nombre_text }}</li>
{% endfor %}
</ul>

gestor/templates/gestor/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'gestor/style.css' %}">
</head>

<body>
    {% if latest_tarea_list %}
    <ul>
        {% for tarea in latest_tarea_list %}
        <li><a href="{% url 'gestor:detail' tarea.id %}">{{ tarea.titulo_text }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No Tareas are available.</p>
    {% endif %}
</body>

</html>